{{ if (.Values.useDomain | default false) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
  - hosts:
      - {{ .Values.domain }}
    secretName: {{ .Release.Name }}-tls
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.dbService }}
            port:
              number: {{ .Values.dbPort }}
{{ end }}
