apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
  annotations:
    external-dns.alpha.kubernetes.io/hostname: staking-dump.w3f.tech
  labels:
    app: {{ .Release.Name }}
spec:
  type: LoadBalancer
  ports:
  - name: port
    targetPort: 5432
    port: 5432
  selector:
    app.kubernetes.io/instance: postgresql-14-read
