environments:
  ci:
  local:

repositories:
- name: w3f
  url: https://w3f.github.io/helm-charts/

releases:

{{- if or (eq .Environment.Name "ci") (eq .Environment.Name "local") }} 

- name: era-scanner
  chart: ../charts/polkadot-era-scanner
  values:
  - ./config/polkadot-era-scanner.yaml.gotmpl  

{{- end }}
